### ISSUE TITLE
Partridge Lake, MI; Site ID 27306

### ISSUE THREAD

**Issue by jessicablois** [NeotomaDB/StewardsDataIssues#3]
From Nicola Cullen on stewards channel on Slack, 1/15/2021: 
I've got a site that I need taken down and don't have the ability to do that myself. Steve Jackson found some completely different information for a site that I'd already uploaded on Jan 13. It actually splits things into two different cores, changes some depths, etc. It's not something that I can just correct. I need to have it taken down so that I can fix everything and upload again as two separate cores. The site is Partridge Lake (MI). Site ID 27306. Dataset ID for pollen is 48863 and charcoal is 48862. 

https://neotomadb.slack.com/archives/CFF9C2J02/p1610771943013400

**Comment by SimonGoring** [comment]
Site has been deleted using the SQL `ts.deletesite` function.
